"""Combine classic game systems and isolated pure modules without runtime tooling.

Domain modules use declarations plus one final named export list. Each is wrapped
in its own closure, so its private names never join the gameplay scope. Their
native ES-module sources can also be imported directly by Node's unit tests.
"""
import re
from .files import read, read_json, source_path, write

EXPORTS = re.compile(r"\nexport\s*\{\s*([A-Za-z0-9_,\s]+)\s*\};\s*$")


def domain_bundle(root, spec):
    source = read(source_path(root, spec["source"]))
    match = EXPORTS.search(source)
    if not match or re.search(r"(?m)^\s*(?:import|export)\b", source[:match.start()]):
        raise ValueError(f"Domain modules require one final named export: {spec['source']}")
    names = [name.strip() for name in match.group(1).split(",") if name.strip()]
    if len(names) != len(set(names)) or not all(re.fullmatch(r"[A-Za-z_$][\w$]*", name) for name in names):
        raise ValueError(f"Invalid domain exports: {spec['source']}")
    return (f"// Domain: {spec['source']}\nconst {spec['namespace']} = (() => {{\n"
            + source[:match.start()] + "\nreturn Object.freeze({" + ", ".join(names) + "});\n})();\n")


def build_bundles(root, config):
    order = read_json(root / "adventure/systems/order.json")
    if len(order) != len(set(order)):
        raise ValueError("Duplicate system in adventure/systems/order.json")
    parts = [read(source_path(root, "adventure/systems/" + name)) for name in order]
    domains = [domain_bundle(root, spec) for spec in config["domains"]]
    write(root / "adventure/game.js",
          "// GENERATED by scripts/build.py — edit adventure/systems/ or adventure/domain/.\n"
          "(() => {\n'use strict';\n" + "\n".join(domains + parts) + "\n})();\n")
    write(root / "adventure/engine.js",
          "// GENERATED by scripts/build.py — edit the individual engine modules.\n"
          + "\n".join(read(source_path(root, name)) for name in config["engineSources"]))
    write(root / "vendor/codemirror/codemirror-python.bundle.js",
          "/* Pinned CodeMirror 5.65.20 + Python addons. MIT license: LICENSE. */\n"
          + "\n".join(read(source_path(root, "vendor/codemirror/" + name))
                       for name in config["editorSources"]))
    return len(order)
