/** Fresh state per session. Nested arrays/objects are never shared between students. */
function createCampaignState({ worldCount, defaultPetId }) {
  return {
    started: false,
    raceStarted: false,
    paused: true,
    level: 0,
    team: '',
    members: [],
    score: 0,
    wrong: 0,
    academicPoints: 0,
    deaths: 0,
    elapsedBase: 0,
    startPerf: 0,
    selected: 0,
    blocks: 12,
    torches: 6,
    chapterTalks: Array.from({ length: worldCount }, () => false),
    terminalSolved: Array.from({ length: worldCount }, () => [false, false]),
    solved: Array.from({ length: worldCount }, () => [false, false, false, false]),
    assessmentPassed: Array.from({ length: worldCount }, () => false),
    bossDefeated: Array.from({ length: worldCount }, () => false),
    checkpoint: { col: 4, label: 'World Start' },
    camera: { x: 0, y: 0, shake: 0 },
    keys: Object.create(null),
    mouse: { x: 0, y: 0, down: false },
    encounterRead: {},
    touchAxis: 0,
    tutorialRead: {},
    currentInteract: null,
    currentShrine: null,
    guideTab: 0,
    toastTimer: 0,
    rewardTimer: 0,
    timerUiTs: 0,
    uiAccumulator: 0,
    gameTime: 0,
    needsRender: true,
    answerStreak: 0,
    bestStreak: 0,
    world: null,
    torchesPlaced: [],
    chests: [],
    enemies: [],
    projectiles: [],
    particles: [],
    loot: [],
    boss: null,
    bossUnlocked: false,
    weapons: ['data_blade'],
    weaponIndex: 0,
    mobKills: { slime: 0, bat: 0, bug: 0 },
    totalMobKills: 0,
    powerId: 'binary_beam',
    powerXp: 0,
    powerCooldown: 0,
    powerBuff: 0,
    debug: false,
    respawnBannerTimer: 0,
    appearance: null,
    petId: defaultPetId
  };
}
function createPlayerState({ maxHealth, airJumps }) {
  return {
    x: 120,
    y: 0,
    w: 24,
    h: 44,
    vx: 0,
    vy: 0,
    dir: 1,
    onGround: false,
    health: maxHealth,
    invuln: 0,
    attack: 0,
    attackCd: 0,
    runFrame: 0,
    runClock: 0,
    airJumps: airJumps,
    dashCd: 0,
    dashTime: 0,
    dashDir: 1,
    dropTimer: 0
  };
}
export { createCampaignState, createPlayerState };
