"""Build a self-contained teacher key from the exact shipped question banks.
Run: python scripts/build_answer_key.py /absolute/path/BITBOUND_v23_Answer_Key.html
This file is a separate teacher deliverable, not part of the student offline pack.
"""
from pathlib import Path
from html import escape as E
import json,sys
ROOT=Path(__file__).resolve().parents[1]
course=json.loads((ROOT/'app/curriculum.json').read_text());story=json.loads((ROOT/'adventure/story.json').read_text());tutorials={q['id']:q for q in json.loads((ROOT/'adventure/tutorials.json').read_text())};encounters=json.loads((ROOT/'adventure/encounter-questions.json').read_text())['items']
blocks=[]
for w,ch in enumerate(course['chapters']):
 region=story['chapters'][w]['region'];blocks.append(f'<section id="world-{w+1}"><h2>World {w+1} · {E(region)}</h2><p>{E(ch["summary"])}</p>')
 items=[q for q in course['items'] if q['chapter']==ch['id']]
 for i,q in enumerate(items):
  label=f'Shrine {i+1}' if i<4 else 'Terminal 1' if i==4 else 'BFS barrier (after Aster)' if w==7 else 'Boss seal / Terminal 2'
  tip=tutorials[q['id']];sol=q['solution']
  blocks.append(f'''<details class="entry" data-search="{E((q['id']+' '+q['title']+' '+ch['title']).lower(),quote=True)}"><summary><span class="tag">{E(q['id'])}</span> {E(label)} · {E(q['title'])}</summary><div class="body">
  <p>{E(q['prompt'])}</p><button class="copy" type="button">Copy Python answer</button><pre class="solution"><code>{E(sol)}</code></pre>
  <p><b>BYTE’s understanding check:</b> {E(tip['question'])}<br><b>Choose {chr(65+tip['answer'])}:</b> {E(tip['choices'][tip['answer']])}</p><p>{E(tip['feedback'])}</p>
  <p><b>Complexity:</b> {E(q['complexity'])}</p>''')
  if q.get('prelude'):blocks.append(f'<p>The checker supplies this setup:</p><pre>{E(q["prelude"])}</pre>')
  blocks.append('<details><summary>Exact challenge test cases</summary><pre>'+E(json.dumps(q['tests'],indent=2,ensure_ascii=False))+'</pre></details></div></details>')
 blocks.append('<h3>Roaming rune encounters</h3><p>Read the displayed topic or encounter ID. These answers do not change the 48 shrine/terminal placements.</p>')
 for q in sorted([q for q in encounters if q['world']==w],key=lambda q:q['sequence']):
  choices=''.join(f'<li{chr(32)+"class=correct" if i==q["answer"] else ""}>{E(choice)}</li>' for i,choice in enumerate(q['choices']))
  blocks.append(f'''<details class="entry" data-search="{E((q['id']+' '+q['topic']+' '+q['prompt']+' '+q['code']).lower(),quote=True)}"><summary><span class="tag">{q['id']}</span> Lesson {q['sequence']} · {E(q['topic'])} <span class="answer">{chr(65+q['answer'])}</span></summary><div class="body"><p><b>Stage {q['stage']} · {E(q['stageTitle'])}</b><br>{E(q['worldContext'])}</p><p>{E(q['prompt'])}</p>{'<pre>'+E(q['code'])+'</pre>' if q['code'] else ''}<ol type="A">{choices}</ol><p><b>Answer {chr(65+q['answer'])}:</b> {E(q['choices'][q['answer']])}</p><p>{E(q['explanation'])}</p></div></details>''')
 blocks.append('</section>')
nav=''.join(f'<a href="#world-{w+1}">World {w+1}</a>' for w in range(8))
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>BITBOUND v23 · Teacher answer key</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#091420;color:#d8e6ed;font:16px/1.6 system-ui,sans-serif}main{max-width:1080px;margin:auto;padding:28px 18px 70px}h1{font-size:clamp(28px,5vw,44px);line-height:1.15;color:#fff1c3}h2{color:#a2e6d6;border-top:1px solid #34515b;padding-top:28px;margin-top:44px}h3{color:#e7cf93}p{max-width:85ch}.eyebrow{letter-spacing:.15em;color:#94d9d4;font-size:13px}nav{display:flex;flex-wrap:wrap;gap:8px}a,button{color:#b6efe0}nav a,button{padding:10px 14px;border:1px solid #426477;background:#142c3c;border-radius:4px;min-height:44px;text-decoration:none;font:inherit;cursor:pointer}.toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}.toolbar input{flex:1;min-width:180px;font:inherit;padding:12px;border:1px solid #507083;background:#0f2333;color:#eef8ff}.entry{border:1px solid #294956;margin:10px 0;background:#0f2030}.entry>summary{padding:15px;cursor:pointer;line-height:1.5}.body{padding:0 18px 20px}.tag{font:13px monospace;color:#afdacc;margin-right:10px}.answer{float:right;background:#294b46;padding:0 10px;border-radius:3px;font-weight:bold}pre{background:#07111c;color:#e4efdb;padding:16px;overflow:auto;font:14px/1.6 ui-monospace,Consolas,monospace;tab-size:4}li{white-space:pre-wrap;padding:6px 8px}.correct{background:#194c40;color:#d0ffe9}.note{border-left:3px solid #e3c779;padding:12px 18px;background:#1b2a32}button:focus-visible,summary:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid #ffe0a1;outline-offset:3px}.copy{float:right;margin:0 0 8px 10px}[hidden]{display:none!important}.status{min-height:1.5em;color:#bce5cd}@media print{:root{color-scheme:light}body,main,.entry,.body,pre{background:white;color:black}main{padding:0}h1,h2,h3,.tag,a{color:black}.toolbar,nav,button,.status{display:none}details>summary{font-weight:bold}details>*{display:block!important}pre{white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid #aaa}.entry{break-inside:avoid}.correct{background:#e2f1e7;color:black}.note{background:white}.answer{color:black;background:#ddd}}</style><main>
<p class="eyebrow">USTP GAME DEV GUILD · TEACHER COPY</p><h1>BITBOUND v23<br>Complete answer key</h1><p>48 Python shrine/terminal solutions · 48 BYTE checks · __COUNT__ roaming encounters</p>
<div class="note"><b>Quick testing:</b> copy a Python answer into its matching challenge editor and select <b>Check challenge</b>. Keep the exact function names, input and output. For BYTE’s check, choose the listed option and select <b>Back to the trail</b>. For rune mobs, search the displayed encounter ID, choose the listed answer (or press its A/B/C key), then continue through up to four rounds. Each shrine requires its teaching stage, and the fixed sentry before it supplies any missing questions. The terminal and exit require all lessons. The correct answer is required; Show a clue is available. Boss coding seals unlock combat; defeating the boss is a separate step.</div>
<h2>Story checkpoints</h2><p>World 1: finish the terminal tasks, defeat the warden, collect the key, then return to the prisoners and press E / Use. World 4: after the guardian, approach the portal to trigger betrayal. In the cell: <b>Read scroll → Inspect dagger → Heat → Hammer → Quench → Turn key</b>. World 8: complete the first terminal, face Aster, solve <b>q48</b> at the BFS barrier, fight Veyr, then fight the fused boss. The fused boss takes damage during recovery: dodge the telegraph, then attack.</p>
<p>Progress saves only when you choose <b>Save file</b>. Start a fresh session to test as another student; import your own save to repeat a later scene. Rune mobs never interrupt boss fights. Each world now follows a fixed, prerequisite-ordered lesson path. A wrong answer, reopening a question or loading an old save cannot skip an unfinished lesson. Once the entire world path is complete, review restarts in the same order. World 4 contains 32 applied problems; old World 4 saves reopen those revised questions without erasing shrines or equipment.</p>
<nav>__NAV__</nav><div class="toolbar"><input id="search" type="search" aria-label="Search question ID or topic" placeholder="Search q48, e08, AVL, queue…"><button id="expand">Open all answers</button><button id="collapse">Close all</button><button id="print">Print / Save PDF</button></div><p id="status" class="status" role="status"></p>
__BLOCKS__
<p>Generated from the exact v23 curriculum, BYTE tutorials and encounter bank. Examples are Python 3. Keep this teacher file separate when distributing the game to students.</p></main><script>
const entries=[...document.querySelectorAll('.entry')],status=document.querySelector('#status');
document.querySelector('#search').oninput=e=>{const term=e.target.value.toLowerCase().trim();for(const row of entries){row.hidden=!row.dataset.search.includes(term);if(term&&!row.hidden)row.open=true;}};
document.querySelector('#expand').onclick=()=>entries.forEach(e=>{if(!e.hidden)e.open=true});document.querySelector('#collapse').onclick=()=>entries.forEach(e=>e.open=false);document.querySelector('#print').onclick=()=>{entries.forEach(e=>e.open=true);window.print()};
for(const b of document.querySelectorAll('.copy'))b.onclick=async()=>{const code=b.parentElement.querySelector('.solution').textContent;try{await navigator.clipboard.writeText(code);status.textContent='Python answer copied.'}catch{const box=document.createElement('textarea');box.value=code;document.body.append(box);box.select();const copied=document.execCommand('copy');box.remove();status.textContent=copied?'Python answer copied.':'Select the Python code and copy it manually.'}};
</script></html>'''
out=Path(sys.argv[1]).resolve();out.parent.mkdir(parents=True,exist_ok=True);out.write_text(page.replace('__NAV__',nav).replace('__BLOCKS__','\n'.join(blocks)).replace('__COUNT__',str(len(encounters))))
print(f'Generated {out.name}: {len(course["items"])} code solutions, {len(tutorials)} tutorial checks, {len(encounters)} encounter answers.')
