"""Deterministic build: bundle adventure systems, adapt tasks, list offline assets.

No transpiler, npm installation or network required.
"""
from pathlib import Path
import hashlib,json,html,re
ROOT=Path(__file__).resolve().parents[1]
order=json.loads((ROOT/'adventure/systems/order.json').read_text())
parts=[(ROOT/'adventure/systems'/name).read_text() for name in order]
# The editor's pinned modules are bundled in dependency order, once at build time.
vendor=['lib/codemirror.js','mode/python/python.js','addon/edit/matchbrackets.js','addon/edit/closebrackets.js','addon/comment/comment.js','addon/hint/show-hint.js','addon/search/searchcursor.js','addon/dialog/dialog.js','addon/search/search.js']
(ROOT/'vendor/codemirror/codemirror-python.bundle.js').write_text('/* Pinned CodeMirror 5.65.20 + Python addons. MIT license: LICENSE. */\n'+'\n'.join((ROOT/'vendor/codemirror'/name).read_text() for name in vendor))
(ROOT/'adventure/game.js').write_text("// GENERATED by scripts/build.py — edit adventure/systems/, not this file.\n(() => {\n'use strict';\n"+'\n'.join(parts)+'\n})();\n')
c=json.loads((ROOT/'app/curriculum.json').read_text())
bank=[dict(id=item['id'],chapter=item['chapter'],title=item['title'],concept=item['concept'],type='code',topic=item['title'],q=item['prompt']) for item in c['items']]
worldIds=[[item['id'] for item in bank if item['chapter']==chapter['id']] for chapter in c['chapters']]
assert len(bank)==48 and all(len(ids)==6 for ids in worldIds)
lessons=[]
for chapter in c['chapters']:
 tasks=[item for item in bank if item['chapter']==chapter['id']]
 lessons.append(dict(name=chapter['title'].upper(),subtitle=chapter['summary'],boss=chapter['boss'],mission='Restore four coding cores, complete two Python terminal tasks, then defeat the guardian.',guide=[dict(title=item['title'],html='<h3>'+html.escape(item['title'])+'</h3><p>'+html.escape(item['concept'])+'</p><p>Open the coding mission for examples, hints, and a runnable Python workspace.</p>') for item in tasks[:4]]))
tutorials=json.loads((ROOT/'adventure/tutorials.json').read_text())
story=json.loads((ROOT/'adventure/story.json').read_text())
encounters=json.loads((ROOT/'adventure/encounter-questions.json').read_text())['items']
assert len(story['chapters'])==len(worldIds)
assert [item['id'] for item in tutorials]==[item['id'] for item in bank]
assert all(len(item['choices'])==3 and 0<=item['answer']<3 for item in tutorials)
q="""(() => {\n'use strict';\nconst encounters=Object.freeze(__ENCOUNTERS__);\nconst bank=Object.freeze(__BANK__);\nconst byId=new Map(bank.map(item=>[item.id,item]));\nconst worldIds=__WORLDS__;\nconst lessons=__LESSONS__;\nconst story=Object.freeze(__STORY__);\nconst tutorials=Object.freeze(__TUTORIALS__);\nfunction get(id){if(!byId.has(id))throw new Error('Unknown mission: '+id);return byId.get(id);}\nfunction validate(){if(bank.length!==48||byId.size!==48||worldIds.length!==8||new Set(worldIds.flat()).size!==48||bank.some(item=>item.type!=='code'||!item.q))throw new Error('Invalid adventure curriculum');return true;}\nwindow.BitboundQuestions=Object.freeze({bank,worldIds,lessons,tutorials,story,encounters,get,validate});\n})();\n"""
payloads={'ENCOUNTERS':encounters,'BANK':bank,'WORLDS':worldIds,'LESSONS':lessons,'TUTORIALS':{item['id']:item for item in tutorials},'STORY':story}
q=re.sub(r'__(BANK|WORLDS|LESSONS|TUTORIALS|STORY|ENCOUNTERS)__',lambda match:json.dumps(payloads[match.group(1)],ensure_ascii=False),q)
(ROOT/'adventure/questions.js').write_text(q)
# Keep independently testable engine modules in one small delivery request.
engine_sources=['../app/music-score.js','core.js','performance.js','terrain-cache.js','touch-controls.js','mentor-sprite.js','mentor-animation.js','player-animation.js','mentor-voice.js','encounter-catalog.js','creature-sprites.js']
(ROOT/'adventure/engine.js').write_text('// GENERATED by scripts/build.py — edit the individual engine modules.\n'+'\n'.join((ROOT/'adventure'/name).read_text() for name in engine_sources))

# Native module imports also carry content hashes. Otherwise an older service
# worker could combine new entry code with the old automatic ProgressStore.
module_hashes={}
visiting=set()
import_pattern=re.compile(r'''(?m)^((?:import|export)[^\n]*?\bfrom\s*["'])(\.[^"'?]+\.js)(?:\?v=[0-9a-f]+)?(["'])''')
def version_module(path):
 if path in module_hashes:return module_hashes[path]
 if path in visiting:raise ValueError('Circular module imports: '+str(path))
 visiting.add(path)
 def version_import(match):
  target=(path.parent/match.group(2)).resolve()
  if not target.is_relative_to(ROOT) or not target.is_file():raise ValueError('Invalid module dependency: '+str(target))
  return match.group(1)+match.group(2)+'?v='+version_module(target)+match.group(3)
 source=import_pattern.sub(version_import,path.read_text())
 path.write_text(source)
 visiting.remove(path)
 module_hashes[path]=hashlib.sha256(path.read_bytes()).hexdigest()[:12]
 return module_hashes[path]
for module_path in sorted((ROOT/'app').glob('*.js')):version_module(module_path.resolve())

# Cache-bust the entry styles/scripts together with their actual content. Old
# service workers see new URLs instead of mixing a new page with an old menu.
asset_revisions={str(path.relative_to(ROOT)):value for path,value in module_hashes.items()}
for entry_name in ['index.html','story.html','app/lab.html']:
 entry_path=ROOT/entry_name
 entry=entry_path.read_text()
 def revision_url(match):
  local=match.group(2)
  asset=(entry_path.parent/local).resolve()
  if not local.endswith(('.css','.js')) or not asset.is_file() or not asset.is_relative_to(ROOT):return match.group(0)
  path=str(asset.relative_to(ROOT))
  revision=hashlib.sha256(asset.read_bytes()).hexdigest()[:12]
  asset_revisions[path]=revision
  return match.group(1)+local+'?v='+revision+'"'
 entry=re.sub(r'((?:src|href)=")([^"?#]+)(?:\?v=[0-9a-f]+)?"',revision_url,entry)
 entry_path.write_text(entry)

# Only runtime files go in the offline pack. Source/tests stay in the download.
files=['index.html','story.html','mode-select.css','styles.css','game-windows.css','manifest.webmanifest']
files += [str(p.relative_to(ROOT)) for folder in ['app','runtime','adventure/assets'] for p in (ROOT/folder).rglob('*') if p.is_file() and '__pycache__' not in p.parts and p.suffix!='.pyc']
files += ['adventure/engine.js','adventure/index.html','adventure/game.js','adventure/questions.js','adventure/style.css','adventure/mobile.css','adventure/story-controls.css']
files += ['docs/TEACHER_GUIDE.md','docs/ARCHITECTURE.md']
files += ['vendor/codemirror/codemirror-python.bundle.js','vendor/codemirror/lib/codemirror.css','vendor/codemirror/addon/hint/show-hint.css','vendor/codemirror/addon/dialog/dialog.css']
files=sorted(set(files))
digest=hashlib.sha256(''.join(hashlib.sha256((ROOT/path).read_bytes()).hexdigest() for path in files).encode()).hexdigest()[:12]
version='bitbound-dsa-'+digest
(ROOT/'offline-manifest.json').write_text(json.dumps({'version':version,'assetRevisions':asset_revisions,'files':files,'bytes':sum((ROOT/path).stat().st_size for path in files),'runtimeCache':'bitbound-python-0.27.7','editorCache':'bitbound-editor-5.65.20','sizes':{path:(ROOT/path).stat().st_size for path in files},'hashes':{path:hashlib.sha256((ROOT/path).read_bytes()).hexdigest() for path in files}},indent=2))
sw=(ROOT/'scripts/sw-template.js').read_text().replace('__CACHE_VERSION__',version).replace('__ASSET_REVISIONS__',json.dumps(asset_revisions))
(ROOT/'sw.js').write_text(sw)
print('Built',len(order),'adventure systems;',len(files),'offline assets;',round(sum((ROOT/path).stat().st_size for path in files)/1e6,2),'MB')
