// GENERATED by scripts/build.py — edit the individual engine modules.
/* Original BITBOUND score. No network, decoded audio files, or game dependency.
 * Each theme has its own melody, harmony, instrumentation and rhythm. Eight-bar
 * phrases develop over a 16-bar arrangement; only a 120ms window is scheduled.
 * Classic script so the same implementation runs in the game bundle and IDE.
 */
(() => {
  'use strict';
  const scales = {major:[0,2,4,5,7,9,11], minor:[0,2,3,5,7,8,10], harmonic:[0,2,3,5,7,8,11], dorian:[0,2,3,5,7,9,10]};
  const notes = text => text.split(' ').map(n => n==='_' ? null : Number(n));
  const catalog = Object.create(null);
  function score(id,name,bpm,root,mode,style,chords,a,b,lead='triangle') {
    catalog[id] = Object.freeze({id,name,bpm,root,scale:scales[mode],style,chords:notes(chords),a:notes(a),b:notes(b),lead,
      volume:style==='ambient'?.44:style==='boss'?.90:.68});
  }
  score('studio','A Spark from the Guild',84,60,'major','ambient','0 3 4 0','0 _ 4 _ 7 _ 9 _','8 _ 7 _ 4 _ 0 _');
  score('choose','Two Roads, One Beginning',104,60,'major','light','0 5 3 4','0 2 4 _ 7 6 4 _ 2 3 4 2 1 _ 0 _','7 _ 9 8 7 4 5 _ 4 2 3 1 0 _ _ _');
  score('setup','An Explorer Takes Shape',112,65,'major','light','0 3 5 4','0 2 4 5 4 _ 2 _ 1 3 5 _ 4 3 2 _','4 6 7 _ 6 4 2 3 4 _ 2 1 0 _ 0 _');
  score('lab','Quiet Keys',76,62,'dorian','ambient','0 3 1 4','4 _ _ 2 _ _ 0 _ 1 _ _ 3 _ 2 _ _','7 _ _ 5 _ 4 _ _ 3 _ 1 _ 0 _ _ _','sine');
  score('practice','One Thought at a Time',88,57,'minor','ambient','0 5 3 4','0 _ 2 _ 4 _ _ 3 2 _ 1 _ 0 _ _ _','4 _ 5 _ 7 _ 5 _ 4 _ 2 _ 1 _ _ _','sine');
  score('lesson','A Guide with Answers',94,67,'major','light','0 3 0 4','2 _ 4 _ 3 2 0 _ 1 _ 3 _ 2 _ _ _','4 _ 6 4 5 _ 3 _ 2 _ 1 2 0 _ _ _');
  score('encounter','Runes in the Grass',120,62,'dorian','light','0 3 6 4','0 _ 4 3 0 2 _ 4 5 _ 4 2 1 _ 0 _','7 5 _ 4 3 _ 2 4 6 _ 5 3 4 _ _ _');
  score('origin','The Stone Opens Its Eyes',82,60,'major','ambient','0 5 3 4','0 _ _ 4 _ _ 7 _ 6 _ 4 _ 2 _ _ _','7 _ 9 _ 8 _ 7 _ 4 _ 2 _ 0 _ _ _');
  score('camp','A Fifth Bowl by the Fire',90,65,'major','light','0 3 5 4','4 _ 2 0 1 _ 2 _ 3 _ 5 4 2 _ 0 _','7 _ 6 4 5 _ 4 _ 2 3 4 _ 1 _ 0 _');
  score('prison','Iron and a Small Ember',68,50,'harmonic','ambient','0 5 3 4','0 _ _ _ 1 _ _ 0 4 _ _ _ 3 _ _ _','2 _ _ 1 0 _ _ _ 6 _ _ 4 0 _ _ _','sine');
  score('betrayal','The Empty Place at the Fire',72,58,'minor','ambient','0 5 1 4','4 _ 2 _ 0 _ _ _ 1 _ 3 _ 2 _ _ _','7 _ 5 _ 4 _ 3 _ 2 _ 1 _ 0 _ _ _');
  score('escape','No Cage Is a Conclusion',122,62,'dorian','march','0 3 6 4','0 2 4 _ 5 4 2 0 3 4 6 _ 5 _ 4 _','7 6 4 5 7 _ 9 7 6 4 3 2 0 _ 0 _');
  score('rivals','Four Claims to One Crown',128,55,'harmonic','march','0 5 3 4','0 _ 1 4 3 _ 2 1 0 4 6 _ 5 4 1 _','7 _ 6 4 5 _ 3 2 1 3 4 6 7 _ _ _','square');
  score('barrier','The Crown’s Last Seal',96,54,'harmonic','ambient','0 1 5 4','0 _ 4 _ 6 _ 7 _ 6 _ 4 _ 1 _ _ _','8 _ 7 _ 6 _ 4 _ 3 _ 1 _ 0 _ _ _');
  score('fusion','A Name Inside the Crown',138,48,'harmonic','march','0 1 5 4','0 0 _ 1 4 _ 6 4 3 _ 1 0 6 _ 4 _','7 6 _ 4 8 7 _ 6 5 3 1 4 0 _ _ _','square');
  score('ending','Beyond the Last Mountain',110,62,'major','light','0 3 5 4','0 2 4 _ 7 _ 9 8 7 4 5 _ 4 2 0 _','7 9 11 _ 10 9 7 _ 8 6 4 2 0 _ _ _');
  score('defeat','Another Attempt, Another Dawn',64,57,'minor','ambient','0 3 5 4','4 _ _ 3 2 _ _ _ 1 _ _ 0 0 _ _ _','2 _ 4 _ 5 _ _ 4 3 _ 1 _ 0 _ _ _','sine');
  score('world0','Stonewake Morning',106,60,'major','light','0 3 5 4','0 2 4 2 5 _ 4 _ 7 6 4 2 1 _ 0 _','4 5 7 _ 9 7 6 _ 5 4 2 3 1 _ 0 _');
  score('world1','Under Thornveil Leaves',98,62,'dorian','forest','0 3 6 0','0 _ 2 4 5 _ 4 2 3 _ 1 0 1 3 2 _','7 _ 5 4 6 _ 5 3 4 2 0 _ 3 1 0 _','sine');
  score('world2','Emberglass Reflections',86,57,'minor','cave','0 5 3 4','4 _ _ 7 _ 5 _ 4 2 _ 3 _ 1 _ _ _','9 _ 7 _ 5 _ _ 4 3 _ 2 _ 0 _ _ _','sine');
  score('world3','Oathforge Procession',116,50,'minor','march','0 6 5 4','0 0 4 _ 3 2 1 _ 0 2 5 _ 4 _ 2 _','7 _ 6 5 4 4 3 2 1 _ 4 3 0 _ 0 _','square');
  score('world4','Ironqueue Echoes',92,52,'harmonic','cave','0 1 5 4','0 _ 1 _ 4 _ 3 1 0 _ _ 6 4 _ _ _','7 _ 6 4 3 _ 1 _ 2 _ 3 1 0 _ _ _');
  score('world5','Across the Broken Drawbridge',124,55,'minor','march','0 5 6 4','0 2 4 7 6 _ 4 2 3 5 7 _ 6 4 2 _','9 7 6 4 5 _ 3 2 4 6 7 6 4 _ 0 _');
  score('world6','The House of Returning Steps',102,54,'harmonic','cave','0 3 1 4','0 4 6 _ 7 6 4 _ 1 4 6 _ 4 1 0 _','7 11 10 _ 8 7 6 _ 4 6 7 _ 3 1 0 _','sine');
  score('world7','The Hall Beneath the Crown',108,48,'harmonic','march','0 5 1 4','0 _ 4 3 1 _ 0 _ 6 _ 4 1 3 _ 4 _','7 _ 8 7 6 _ 4 _ 5 3 1 _ 4 _ 0 _','square');
  score('boss0','Break the Warden’s Chains',144,50,'minor','boss','0 5 6 4','0 0 4 3 0 2 5 4 3 1 4 2 1 0 1 _','7 6 4 5 7 4 3 2 5 4 2 1 0 4 0 _');
  score('boss1','Roots around the Colossus',150,55,'dorian','boss','0 3 6 4','0 3 4 _ 6 4 3 1 0 2 3 5 4 _ 2 0','7 5 4 6 8 6 5 3 4 7 6 4 3 1 0 _','square');
  score('boss2','Brass and Burning Glass',156,57,'harmonic','boss','0 1 5 4','4 0 1 4 6 _ 4 3 1 0 3 1 0 _ 6 4','7 8 7 4 6 4 3 1 5 3 1 4 6 _ 7 _');
  score('boss3','The Castellan’s Broken Oath',148,48,'minor','boss','0 6 3 4','0 0 3 4 0 _ 6 5 4 3 1 0 3 _ 4 _','7 7 6 4 5 3 4 2 1 4 6 4 0 _ 0 _','square');
  score('boss4','No Chain Can Hold',158,52,'harmonic','boss','0 5 1 4','0 1 0 4 3 1 4 6 7 _ 6 4 1 3 0 _','7 6 4 7 8 7 4 6 5 3 1 4 0 1 0 _');
  score('boss5','Revenant at the Red Gate',162,55,'minor','boss','0 3 5 4','7 4 0 2 3 5 4 2 0 2 4 6 5 3 1 _','9 7 6 4 7 5 4 2 3 4 6 7 4 2 0 _','square');
  score('boss6','The Sentinel Answers Twice',154,54,'harmonic','boss','0 1 3 4','0 4 6 4 1 4 6 4 3 5 7 5 4 6 8 _','7 11 10 8 7 6 4 3 1 4 6 4 0 1 0 _');
  score('boss7','Veyr, the Gilded Tyrant',164,48,'harmonic','boss','0 5 1 4','0 0 4 6 7 6 4 1 3 1 0 4 6 4 1 _','7 8 7 6 4 7 6 4 5 3 1 4 6 7 0 _','square');
  score('paladin','Aster, the Oath Forsaken',152,53,'minor','boss','0 3 6 4','4 4 2 0 1 3 2 _ 5 4 3 1 0 2 4 _','7 6 4 2 3 5 4 _ 8 7 5 3 4 2 0 _');
  score('fused','Stone against the Fused Crown',174,50,'harmonic','boss','0 1 5 4','0 4 1 6 4 7 6 4 8 7 6 4 3 1 0 4','7 11 10 8 7 6 4 6 9 8 7 6 4 1 0 _','square');
  const frequency = midi => 440 * Math.pow(2,(midi-69)/12);
  function pitch(t,degree,octave=0) {
    return t.root + octave*12 + Math.floor(degree/7)*12 + t.scale[((degree%7)+7)%7];
  }
  // Pure arrangement: shared by the live player, audio tests and score previews.
  function events(t,step) {
    const bar=Math.floor(step/8)%16, beat=step%8, phrase=bar%8;
    const chord=t.chords[Math.floor(phrase/2)%t.chords.length];
    const motif=bar>=8?t.b:t.a, degree=motif[(phrase*8+beat)%motif.length];
    const d=30/t.bpm, out=[], busy=t.style==='boss', ambient=t.style==='ambient';
    const add=(n,span,type,gain)=>out.push({freq:frequency(pitch(t,n)),dur:span*d,type,gain});
    if(degree!==null && !(ambient&&bar%4===3&&beat>3))add(degree,.78,t.lead,busy?.058:.048);
    if(beat===0 || (!ambient && (beat===4 || (busy && [3,6].includes(beat)))))
      add(chord-14+(beat===6?4:0),busy?1.2:2.8,'triangle',busy?.082:.058);
    if(beat===0)for(const n of [chord,chord+2,chord+4])add(n-7,ambient?6.5:3.7,'sine',.021);
    if(!ambient&&bar>=4&&beat%2===1)add(chord+[0,2,4,2][Math.floor(beat/2)]+7,.5,'sine',.017);
    if(!ambient){
      if(beat===0||beat===4||(busy&&beat===6))out.push({drum:'kick',gain:busy?.15:.07});
      if(beat===2||beat===6)out.push({drum:'snare',gain:busy?.055:.017});
      if(busy||beat%2===1)out.push({drum:'hat',gain:busy?.024:.011});
      if(busy&&bar%4===3&&beat>=5)out.push({drum:'snare',gain:.04});
    }
    return out;
  }
  class Player {
    constructor(ctx,output,{setTimer=(fn,ms)=>setInterval(fn,ms),clearTimer=id=>clearInterval(id)}={}) {
      this.ctx=ctx;this.output=output;this.setTimer=setTimer;this.clearTimer=clearTimer;
      this.timer=null;this.track=null;this.enabled=true;this.background=false;
      this.voices=new Set();this.bus=null;this.step=0;this.next=0;
      this.noise=null;this.failed=false;
    }
    setTrack(id){
      if(!catalog[id])throw new Error('Unknown music theme: '+id);
      if(this.track===id)return;
      this.halt(.18);this.track=id;this.step=0;this.start();
    }
    setEnabled(on){this.enabled=!!on;if(on)this.start();else this.halt(.04);}
    setBackground(hidden){this.background=!!hidden;if(hidden)this.halt(0);else this.start();}
    start(){
      if(this.failed||this.timer!==null||!this.enabled||this.background||!this.track||this.ctx.state!=='running')return;
      try{
      this.bus=this.ctx.createGain();this.bus.gain.setValueAtTime(0,this.ctx.currentTime);
      this.bus.gain.linearRampToValueAtTime(catalog[this.track].volume,this.ctx.currentTime+.25);
      this.bus.connect(this.output);this.next=this.ctx.currentTime+.025;
      this.pump();if(!this.failed)this.timer=this.setTimer(()=>this.pump(),40);
      }catch{this.fail();}
    }
    halt(fade=0){
      if(this.timer!==null){this.clearTimer(this.timer);this.timer=null;}
      const bus=this.bus;this.bus=null;
      if(bus){const now=this.ctx.currentTime;bus.gain.cancelScheduledValues(now);bus.gain.setTargetAtTime(.0001,now,Math.max(.005,fade/4));}
      for(const voice of [...this.voices]){
        if(voice.bus!==bus&&fade>0)continue;
        try{voice.source.stop(this.ctx.currentTime+fade+.005);}catch{}
        if(fade===0)this.release(voice);
      }
      if(bus&&![...this.voices].some(v=>v.bus===bus))bus.disconnect();
    }
    release(v){
      if(!this.voices.delete(v))return;
      v.source.onended=null;for(const n of v.nodes)n.disconnect();
      if(v.bus!==this.bus&&![...this.voices].some(other=>other.bus===v.bus))v.bus.disconnect();
    }
    fail(){this.failed=true;try{this.halt(0);}catch{} /* Optional music cannot block play. */}
    pump(){
      if(!this.enabled||this.background||!this.bus||this.ctx.state!=='running'){this.halt(0);return;}
      // A stalled tab never catches up by emitting a burst of missed notes.
      if(this.next<this.ctx.currentTime-.12)this.next=this.ctx.currentTime+.025;
      const t=catalog[this.track];let budget=4;
      try{
      while(this.next<this.ctx.currentTime+.12&&budget-->0){
        for(const e of events(t,this.step))this.voice(e,this.next);
        this.step=(this.step+1)%128;this.next+=30/t.bpm;
      }
      }catch{this.fail();}
    }
    voice(e,at){
      if(this.voices.size>=40||!this.bus)return;
      const ctx=this.ctx,amp=ctx.createGain(),nodes=[amp];let source,dur=e.dur||.07;
      if(e.drum&&e.drum!=='kick'){
        if(!this.noise){this.noise=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*.2),ctx.sampleRate);const data=this.noise.getChannelData(0);let n=271;
          for(let i=0;i<data.length;i++){n=(Math.imul(n,1664525)+1013904223)>>>0;data[i]=n/2147483648-1;}}
        source=ctx.createBufferSource();source.buffer=this.noise;
        const filter=ctx.createBiquadFilter();filter.type='highpass';filter.frequency.value=e.drum==='hat'?6200:1500;
        source.connect(filter);filter.connect(amp);nodes.push(filter);dur=e.drum==='hat'?.035:.11;
      }else{
        source=ctx.createOscillator();source.type=e.drum?'sine':e.type;
        source.frequency.setValueAtTime(e.drum?125:e.freq,at);
        if(e.drum)source.frequency.exponentialRampToValueAtTime(42,at+.08);
        if(e.type==='square'){
          const filter=ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=2100;
          source.connect(filter);filter.connect(amp);nodes.push(filter);
        }else source.connect(amp);
      }
      nodes.push(source);const gain=e.type==='square'?e.gain*.60:e.gain;
      amp.gain.setValueAtTime(.0001,at);amp.gain.linearRampToValueAtTime(gain,at+.008);
      if(!e.drum){amp.gain.linearRampToValueAtTime(gain*.72,at+dur*.20);amp.gain.setValueAtTime(gain*.72,at+dur*.65);}
      amp.gain.exponentialRampToValueAtTime(.0001,at+dur);amp.connect(this.bus);
      const v={source,nodes,bus:this.bus};this.voices.add(v);source.onended=()=>this.release(v);
      source.start(at);source.stop(at+dur+.01);
    }
    destroy(){this.halt(0);this.track=null;this.noise=null;}
  }
  // This setting contains only music preference, never student work/progress.
  function preference(value){try{if(typeof value==='boolean')sessionStorage.setItem('bitbound-music',value?'on':'off');return sessionStorage.getItem('bitbound-music')!=='off';}catch{return typeof value==='boolean'?value:true;}}
  window.BitboundMusic=Object.freeze({catalog:Object.freeze(catalog),events,Player,preference});
})();

(() => {
'use strict';

/** Compact a dense array without allocating a replacement array. */
function compactInPlace(list,keep,recycle){
  let write=0;
  for(let read=0;read<list.length;read++){
    const item=list[read];
    if(keep(item))list[write++]=item;
    else if(recycle)recycle(item);
  }
  list.length=write;
  return list;
}

/** Add to a bounded dense store, reclaiming dead entries before replacing one. */
function pushBounded(list,item,limit,{keep=value=>value&&value.alive!==false,replace=value=>value&&value.alive!==false}={}){
  if(list.length>=limit)compactInPlace(list,keep);
  if(list.length<limit){list.push(item);return item;}
  const index=list.findIndex(replace);
  if(index<0)return null;
  list[index]=item;
  return item;
}

/** Reuses short-lived objects to avoid garbage-collector spikes during combat. */
class ObjectPool{
  constructor(factory,reset,maxFree=256){this.factory=factory;this.reset=reset;this.maxFree=maxFree;this.free=[];}
  acquire(seed){const value=this.free.pop()||this.factory();this.reset(value,seed);return value;}
  release(value){if(this.free.length<this.maxFree)this.free.push(value);}
  clear(){this.free.length=0;}
  get available(){return this.free.length;}
}

/** Keeps only the most recently used heavy assets instead of growing forever. */
class LruCache{
  constructor(limit=4){this.limit=Math.max(1,limit|0);this.values=new Map();}
  has(key){return this.values.has(key);}
  get(key){
    if(!this.values.has(key))return undefined;
    const value=this.values.get(key);this.values.delete(key);this.values.set(key,value);return value;
  }
  set(key,value){
    if(this.values.has(key))this.values.delete(key);this.values.set(key,value);
    while(this.values.size>this.limit)this.values.delete(this.values.keys().next().value);
    return value;
  }
  delete(key){return this.values.delete(key);}
  clear(){this.values.clear();}
  keys(){return this.values.keys();}
  get size(){return this.values.size;}
}

/**
 * One-dimensional spatial hash for side-scrolling worlds.
 * Rebuild is O(n); local collision queries inspect only overlapping buckets.
 */
class SpatialHash1D{
  constructor(cellSize=128){
    this.cellSize=Math.max(16,cellSize|0);this.buckets=new Map();this.bucketPool=[];
    this.seen=new WeakMap();this.querySerial=0;
  }
  clear(){
    for(const bucket of this.buckets.values()){bucket.length=0;this.bucketPool.push(bucket);}
    this.buckets.clear();
  }
  rebuild(items,getBounds=null,isActive=value=>value&&value.alive!==false){
    this.clear();
    for(const item of items){
      if(!isActive(item))continue;
      const bounds=getBounds?getBounds(item):null;
      const first=Math.floor((bounds?bounds[0]:item.x)/this.cellSize);
      const last=Math.floor((bounds?bounds[1]:item.x+(item.w||0))/this.cellSize);
      for(let key=first;key<=last;key++){
        let bucket=this.buckets.get(key);
        if(!bucket){bucket=this.bucketPool.pop()||[];this.buckets.set(key,bucket);}
        bucket.push(item);
      }
    }
    return this;
  }
  visit(min,max,visitor,stopOnTruthy=false){
    this.querySerial=(this.querySerial+1)>>>0;
    if(this.querySerial===0){this.seen=new WeakMap();this.querySerial=1;}
    const serial=this.querySerial,first=Math.floor(min/this.cellSize),last=Math.floor(max/this.cellSize);
    for(let key=first;key<=last;key++){
      const bucket=this.buckets.get(key);if(!bucket)continue;
      for(const item of bucket){
        if(this.seen.get(item)===serial)continue;
        this.seen.set(item,serial);
        if(visitor(item)&&stopOnTruthy)return true;
      }
    }
    return false;
  }
  some(min,max,visitor){return this.visit(min,max,visitor,true);}
  forEach(min,max,visitor){this.visit(min,max,visitor,false);}
}

/** Avoids redundant DOM writes in the frequently refreshed HUD. */
class DomWriteCache{
  text(element,value){if(!element)return;const next=String(value);if(element.textContent!==next)element.textContent=next;}
  style(element,property,value){if(element&&element.style[property]!==value)element.style[property]=value;}
  toggle(element,className,force){if(element&&element.classList.contains(className)!==Boolean(force))element.classList.toggle(className,Boolean(force));}
}

window.BitboundCore=Object.freeze({compactInPlace,pushBounded,ObjectPool,LruCache,SpatialHash1D,DomWriteCache});
})();

/* Independent timing and quality policy. No game state, DOM, or rendering code. */
(() => {
'use strict';

const QUALITY = Object.freeze({
  standard: Object.freeze({fps:60, uiInterval:.12, particles:180, projectiles:140, loot:20, particleScale:.85, stars:36, richFx:true}),
  low: Object.freeze({fps:30, uiInterval:.16, particles:72, projectiles:140, loot:20, particleScale:.45, stars:12, richFx:false}),
  eco: Object.freeze({fps:20, uiInterval:.2, particles:36, projectiles:140, loot:20, particleScale:.25, stars:0, richFx:false})
});

/** Fixed 60 Hz physics regardless of display/quality rate. Catch-up work is bounded. */
class FixedStepClock {
  constructor({hz=60,maxSteps=4}={}) {
    this.step=1/hz;
    this.maxSteps=maxSteps;
    this.reset();
  }
  reset() { this.last=null; this.accumulator=0; }
  advance(timestamp,update) {
    if(this.last===null) { this.last=timestamp; return 0; }
    const elapsed=Math.max(0,(timestamp-this.last)/1000);
    this.last=timestamp;
    this.accumulator=Math.min(this.accumulator+elapsed,this.step*this.maxSteps);
    let steps=0;
    while(this.accumulator+1e-9>=this.step && steps<this.maxSteps) {
      update(this.step);
      this.accumulator=Math.max(0,this.accumulator-this.step);
      steps++;
    }
    return steps;
  }
}

/** Sleep between render deadlines instead of polling every display refresh. */
class FrameScheduler {
  constructor({render,shouldContinue,frameMs,now=()=>performance.now(),
    requestFrame=fn=>requestAnimationFrame(fn),cancelFrame=id=>cancelAnimationFrame(id),
    setTimer=(fn,ms)=>setTimeout(fn,ms),clearTimer=id=>clearTimeout(id)}) {
    Object.assign(this,{render,shouldContinue,frameMs,now,requestFrame,cancelFrame,setTimer,clearTimer});
    this.frame=null; this.timer=null; this.deadline=null;
    this.onFrame=this.onFrame.bind(this);
    this.afterWait=()=>{this.timer=null;this.frame=this.requestFrame(this.onFrame);};
  }
  request() {
    if(this.frame!==null || this.timer!==null)return;
    this.deadline=this.now();
    this.frame=this.requestFrame(this.onFrame);
  }
  arm() {
    if(this.frame!==null || this.timer!==null)return;
    // A sub-millisecond lead avoids waking multiple times on high-refresh displays.
    const wait=this.deadline-this.now()-.5;
    if(wait>1)this.timer=this.setTimer(this.afterWait,wait);
    else this.frame=this.requestFrame(this.onFrame);
  }
  onFrame(timestamp) {
    this.frame=null;
    if(timestamp+.75<this.deadline) { this.arm(); return; }
    this.render(timestamp);
    if(!this.shouldContinue()) { this.stop(); return; }
    const interval=this.frameMs();
    this.deadline=(this.deadline??timestamp)+interval;
    if(this.deadline<=timestamp)this.deadline=timestamp+interval;
    this.arm();
  }
  stop() {
    if(this.frame!==null)this.cancelFrame(this.frame);
    if(this.timer!==null)this.clearTimer(this.timer);
    this.frame=null; this.timer=null; this.deadline=null;
  }
}

/** Downgrade after sustained expensive frames; never oscillate quality per frame. */
class QualityGovernor {
  constructor(windowSize=60) { this.windowSize=windowSize; this.reset(); }
  reset() { this.count=0;this.total=0;this.slow=0;this.previous=null; }
  record(timestamp,costMs,budgetMs) {
    const gap=this.previous===null?0:timestamp-this.previous;
    this.previous=timestamp;
    this.total+=Math.max(0,costMs);
    if(gap>budgetMs*1.6)this.slow++;
    if(++this.count<this.windowSize)return false;
    const overloaded=this.total/this.count>budgetMs*.45 || this.slow/this.count>.2;
    this.count=0;this.total=0;this.slow=0;
    return overloaded;
  }
}

window.BitboundPerformance=Object.freeze({QUALITY,FixedStepClock,FrameScheduler,QualityGovernor});
})();

/* Bounded terrain textures. Dynamic actors, landmarks and effects render separately. */
(() => {
'use strict';
class TerrainCache {
  constructor({tileSize=32,chunkTiles=8,limit=28,createSurface,paintTile}) {
    Object.assign(this,{tileSize,chunkTiles,limit,createSurface,paintTile});
    this.pixels=tileSize*chunkTiles;
    this.entries=new Map();
    this.pool=[];
    this.world=null;
    this.unavailable=false;
    this.stats={builds:0,hits:0,invalidations:0};
  }
  reset(world=null) {
    for(const entry of this.entries.values())this.pool.push(entry);
    this.entries.clear();
    this.world=world;
    this.trimPool();
  }
  trimPool() {
    while(this.pool.length>this.limit){const entry=this.pool.pop();entry.surface.width=0;entry.surface.height=0;}
  }
  key(column,row) { return row*this.columns+column; }
  invalidate(column,row) {
    if(!this.world || row<0 || column<0)return;
    const key=this.key(Math.floor(column/this.chunkTiles),Math.floor(row/this.chunkTiles));
    const entry=this.entries.get(key);
    if(entry){this.entries.delete(key);this.pool.push(entry);this.stats.invalidations++;}
  }
  get(column,row,theme) {
    const key=this.key(column,row);
    let entry=this.entries.get(key);
    if(entry){this.entries.delete(key);this.entries.set(key,entry);this.stats.hits++;return entry;}
    if(this.entries.size>=this.limit){const first=this.entries.keys().next().value;entry=this.entries.get(first);this.entries.delete(first);}
    else entry=this.pool.pop();
    if(!entry){
      try{
        const surface=this.createSurface(this.pixels,this.pixels);
        const context=surface.getContext('2d',{alpha:true});
        if(!context){this.unavailable=true;return null;}
        entry={surface,context};
      }catch{this.unavailable=true;return null;}
    }
    const {context}=entry,x=column*this.pixels,y=row*this.pixels;
    context.setTransform(1,0,0,1,0,0);
    context.clearRect(0,0,this.pixels,this.pixels);
    context.imageSmoothingEnabled=false;
    context.lineWidth=1;
    context.translate(-x,-y);
    const firstColumn=column*this.chunkTiles,firstRow=row*this.chunkTiles;
    for(let r=firstRow;r<Math.min(firstRow+this.chunkTiles,this.world.tiles.length);r++){
      const tiles=this.world.tiles[r];
      for(let c=firstColumn;c<Math.min(firstColumn+this.chunkTiles,tiles.length);c++){
        if(tiles[c])this.paintTile(context,c,r,tiles[c],theme);
      }
    }
    context.setTransform(1,0,0,1,0,0);
    this.entries.set(key,entry);
    this.stats.builds++;
    return entry;
  }
  draw(target,world,theme,x,y,width,height) {
    if(this.unavailable)return false;
    if(this.world!==world)this.reset(world);
    this.columns=Math.ceil(world.tiles[0].length/this.chunkTiles);
    const rows=Math.ceil(world.tiles.length/this.chunkTiles);
    const c0=Math.max(0,Math.floor(x/this.pixels)),r0=Math.max(0,Math.floor(y/this.pixels));
    const c1=Math.min(this.columns-1,Math.floor((x+width-1)/this.pixels));
    const r1=Math.min(rows-1,Math.floor((y+height-1)/this.pixels));
    for(let row=r0;row<=r1;row++)for(let col=c0;col<=c1;col++){
      const entry=this.get(col,row,theme);
      if(!entry)return false;
      target.drawImage(entry.surface,col*this.pixels,row*this.pixels);
    }
    return true;
  }
  get bytes() { return (this.entries.size+this.pool.length)*this.pixels*this.pixels*4; }
}
window.BitboundTerrain=Object.freeze({TerrainCache});
})();

/* Event-driven joystick: one captured pointer; no animation loop or polling. */
(() => {
  'use strict';
  class Joystick {
    constructor(element, knob, {enabled, move, deadZone = 0.16}) {
      this.element = element;
      this.knob = knob;
      this.enabled = enabled;
      this.move = move;
      this.deadZone = deadZone;
      this.pointerId = null;
      this.bounds = null;
      element.addEventListener('pointerdown', event => this.start(event));
      element.addEventListener('pointermove', event => this.drag(event));
      for (const type of ['pointerup', 'pointercancel', 'lostpointercapture']) {
        element.addEventListener(type, event => {
          if (event.pointerId === this.pointerId) this.reset();
        });
      }
    }
    start(event) {
      if (!this.enabled() || this.pointerId !== null || (event.button != null && event.button !== 0)) return;
      event.preventDefault();
      this.bounds = this.element.getBoundingClientRect();
      this.pointerId = event.pointerId;
      this.element.setPointerCapture(event.pointerId);
      this.element.classList.add('active');
      this.drag(event);
    }
    drag(event) {
      if (event.pointerId !== this.pointerId) return;
      if (!this.enabled()) { this.reset(); return; }
      event.preventDefault();
      const box = this.bounds;
      const radius = Math.max(1, Math.min(box.width, box.height) * 0.32);
      const dx = event.clientX - box.left - box.width / 2;
      const dy = event.clientY - box.top - box.height / 2;
      const length = Math.hypot(dx, dy);
      const scale = length > radius ? radius / length : 1;
      const x = dx * scale, y = dy * scale;
      const axis = x / radius;
      const magnitude = Math.abs(axis);
      this.move(magnitude <= this.deadZone ? 0 : Math.sign(axis) * (magnitude - this.deadZone) / (1 - this.deadZone));
      this.knob.style.transform = `translate(${x}px, ${y}px)`;
    }
    reset() {
      const pointer = this.pointerId;
      this.pointerId = null;
      this.bounds = null;
      this.move(0);
      this.knob.style.transform = 'translate(0px, 0px)';
      this.element.classList.remove('active');
      if (pointer !== null && this.element.hasPointerCapture?.(pointer)) this.element.releasePointerCapture(pointer);
    }
  }
  window.BitboundTouch = Object.freeze({Joystick});
})();

/* Byte: six cached, reference-inspired poses. The world sprite stands one head taller than the player.
   Source art is 48 × 88 for a readable portrait; no images/fonts/network needed. */
(() => {
  'use strict';
  const WIDTH=24,HEIGHT=44,SCALE=2,WORLD_WIDTH=36,WORLD_HEIGHT=56,POSES=['idle','wave','wave-high','shrug','cheer','blink'];
  function paint(canvas,pose,part=null){
    const g=canvas.getContext('2d');
    if(!part&&window.BitboundCharacterRig){
      const motion=pose==='cheer'?'cheer':pose.startsWith('wave')?'wave':pose==='shrug'?'speak':'listen';
      window.BitboundCharacterRig.paint(g,{kind:'byte',x:24,foot:86,scale:.88,face:1,motion,
        phase:pose==='wave-high'?.6:pose==='wave'?.32:.5,mood:pose==='blink'?'blink':pose==='shrug'?'shock':'smile',
        armed:false,precise:true,expression:{blink:pose==='blink',speaking:pose==='shrug',syllable:1}});return;
    }
    const ink='#101c25',skin='#cf8c55',lit='#f1b976',shade='#a9643a',navy='#1e3b62';
    const rect=(c,x,y,w,h)=>{g.fillStyle=c;g.fillRect(x,y,w,h);};
    const poly=(c,points)=>{g.fillStyle=c;g.beginPath();points.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.closePath();g.fill();};
    const line=(c,width,points)=>{g.strokeStyle=c;g.lineWidth=width;g.beginPath();points.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.stroke();};
    const lift=pose==='cheer'?-2:pose==='shrug'?1:0;
    if(!part){
    // Shoes and separated trouser legs: soft gray folds and visible cargo pockets.
    poly(ink,[[12,58],[38,58],[37,80],[42,84],[42,88],[28,88],[25,72],[23,86],[9,87],[7,83],[12,79]]);
    poly('#626764',[[13,58],[25,61],[22,80],[11,81]]);poly('#77786d',[[26,61],[37,58],[35,80],[28,82]]);
    poly('#454f50',[[21,65],[24,63],[22,80],[18,81]]);poly('#4b5351',[[30,71],[35,68],[33,81],[29,82]]);
    rect('#8b8d7e',14,64,5,2);rect('#3b484d',12,67,6,6);rect('#777d70',13,67,5,2);rect('#545e5a',31,62,5,6);
    poly('#14232d',[[11,79],[21,80],[22,86],[8,86],[8,83]]);poly('#14232d',[[28,80],[35,78],[40,83],[41,86],[28,86]]);
    rect('#cad2cb',8,85,14,2);rect('#c2cfcd',29,85,12,2);rect('#91adb9',11,81,7,1);rect('#91adb9',30,81,5,1);
    }
    g.save();g.translate(0,lift);
    if(!part||part==='body'){
    // Blue hood and short-sleeved shirt, a little wider than the backpack.
    poly(ink,[[14,25],[32,25],[41,32],[40,60],[35,65],[14,64],[8,58],[7,34]]);
    poly(navy,[[14,27],[32,27],[39,33],[37,58],[34,62],[15,61],[10,55],[9,34]]);
    poly('#2f5380',[[11,31],[16,29],[15,44],[8,45],[7,35]]);poly('#294972',[[33,29],[39,32],[42,42],[34,45]]);
    line('#142944',3,[[13,29],[19,35],[26,37],[34,29]]);line('#466583',1,[[16,29],[22,33],[27,33],[31,29]]);
    }
    if(!part){
    // Arms have distinct gestures, leaving the face and pack readable.
    if(pose==='wave'||pose==='wave-high'||pose==='cheer'){
      poly(ink,[[7,40],[14,43],[10,55],[4,55],[1,41],[0,31],[6,29]]);
      poly(skin,[[8,42],[12,43],[8,51],[5,49],[3,38],[7,37]]);
      const handY=pose==='wave-high'?22:28;
      poly(lit,[[2,handY],[4,handY-4],[6,handY-3],[6,handY+5],[8,handY+2],[10,handY+3],[8,handY+11],[4,handY+12],[1,handY+7],[0,handY+1]]);
      rect(shade,4,handY+4,1,5);rect('#ffcf90',2,handY+1,2,5);
    }else{
      poly(ink,[[7,41],[14,43],[11,56],[3,57],[0,48],[3,42]]);
      poly(skin,[[8,43],[12,44],[9,53],[5,54],[2,49],[3,45]]);
      poly(lit,pose==='shrug'?[[1,42],[3,39],[5,43],[9,44],[9,49],[5,51],[1,48]]:[[1,46],[3,44],[5,48],[9,49],[8,54],[4,54],[1,51]]);
      rect(shade,5,49,1,3);
    }
    if(pose==='cheer'){
      poly(ink,[[34,41],[41,39],[45,30],[46,19],[41,17],[37,22],[39,31]]);
      poly(lit,[[38,40],[41,40],[45,31],[44,25],[40,26],[41,32]]);
      poly(skin,[[39,18],[45,17],[47,22],[44,27],[39,26],[37,22]]);rect(lit,40,18,4,3);
    }else{
      poly(ink,[[34,42],[41,40],[44,48],[47,46],[48,54],[42,58],[37,55]]);
      poly(skin,[[36,43],[40,42],[42,52],[45,50],[46,54],[42,56],[39,53]]);
      poly(lit,pose==='shrug'?[[39,46],[39,42],[41,41],[43,45],[45,42],[47,44],[47,50],[43,52],[40,50]]:[[41,49],[41,45],[43,44],[44,49],[47,46],[48,48],[47,54],[43,56]]);
    }
    }
    if(!part||part==='body'){
    // Broad charcoal backpack, with a curved top, double seams and a zipped pocket.
    line('#0d1920',5,[[13,29],[18,40],[20,52]]);line('#738078',1,[[13,30],[17,40]]);
    line('#0c171d',5,[[33,29],[29,40],[29,50]]);line('#6f7e74',1,[[33,30],[30,38]]);
    poly('#0c171c',[[20,34],[28,34],[34,39],[36,48],[36,59],[32,63],[18,64],[12,60],[12,46],[15,38]]);
    poly('#3d4646',[[20,37],[28,36],[32,40],[34,48],[33,58],[30,61],[18,61],[15,58],[15,45],[17,40]]);
    poly('#505750',[[19,39],[28,38],[31,41],[31,44],[17,45],[17,42]]);
    line('#748077',1,[[16,58],[15,47],[17,41],[21,38],[28,38],[32,43],[33,56],[31,60],[20,61],[16,58]]);
    poly('#252f32',[[18,46],[30,45],[32,49],[31,57],[28,59],[18,59],[16,55],[16,49]]);
    line('#727d73',1,[[18,48],[29,47],[31,49]]);rect('#c0c8b4',28,48,1,4);rect('#a0b09d',28,51,2,1);
    rect('#16242b',13,49,2,7);rect('#8b9480',32,49,1,3);rect('#5d726c',19,59,9,1);
    }
    if((!part||part==='head')&&window.BitboundFaceArt){
      g.save();g.translate(-8,0);g.scale(1,88/96);
      window.BitboundFaceArt.paint(g,{kind:'byte',mood:pose==='blink'?'blink':pose==='shrug'?'shock':'smile'});g.restore();
    }else if(!part||part==='head'){
    // Tan face, ears, an open smile and chunky, tousled black hair.
    rect(shade,20,24,9,6);rect(skin,22,24,6,5);
    poly(ink,[[13,8],[17,4],[30,4],[35,9],[35,22],[31,28],[23,30],[16,26],[12,19]]);
    poly(skin,[[15,10],[20,6],[29,7],[33,11],[32,23],[28,27],[22,27],[17,24],[14,19]]);
    poly(lit,[[18,11],[29,10],[31,13],[31,22],[27,25],[21,24],[17,20],[17,14]]);
    rect(skin,11,15,4,7);rect('#e9ac6b',12,16,2,4);rect(skin,33,14,3,7);rect(lit,33,15,2,3);
    poly('#131e20',[[12,16],[10,11],[13,6],[12,4],[17,4],[18,0],[22,2],[25,0],[28,2],[32,1],[33,5],[36,8],[35,15],[32,16],[31,10],[28,8],[26,12],[24,9],[21,11],[20,8],[17,10],[15,10],[15,17]]);
    poly('#334139',[[14,6],[18,3],[20,4],[17,6],[14,10]]);poly('#344139',[[23,4],[26,2],[29,4],[27,5]]);rect('#263831',31,6,2,2);
    rect('#34352a',18,13,5,1);rect('#34352a',27,12,4,1);
    if(pose==='blink') {rect('#373f33',19,16,4,1);rect('#373f33',27,15,4,1);}
    else {rect('#fff1d4',18,15,5,5);rect('#fff1d4',27,14,4,5);rect('#172a31',20,15,2,4);rect('#172a31',28,14,2,4);rect('#fffce4',20,15,1,1);rect('#fffce4',28,14,1,1);}
    rect('#be783f',24,18,2,3);rect('#e7a363',23,21,4,1);
    if(pose==='shrug'){poly('#633d29',[[21,23],[25,22],[29,23],[28,25],[22,25]]);}
    else {poly('#78432f',[[19,21],[24,23],[30,21],[29,25],[26,27],[22,26]]);poly('#fff4da',[[20,22],[25,23],[29,22],[27,24],[23,24]]);rect('#d87c57',24,25,3,1);}
    }
    g.restore();
  }
  function create(document){
    return Object.freeze(POSES.map(pose=>{const canvas=document.createElement('canvas');canvas.width=WIDTH*SCALE;canvas.height=HEIGHT*SCALE;paint(canvas,pose);return canvas;}));
  }
  function worldFrames(document,frames){
    return Object.freeze(frames.map((frame,index)=>{
      const small=document.createElement('canvas');small.width=WORLD_WIDTH;small.height=WORLD_HEIGHT;
      const g=small.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(frame,0,0,WORLD_WIDTH,WORLD_HEIGHT);
      // Align the small smile with the resized face.
      if(!window.BitboundFaceArt&&POSES[index]!=='shrug'){
        g.fillStyle='#77432d';g.fillRect(14,14,8,3);
        g.fillStyle='#fff2d5';g.fillRect(15,14,6,1);
        g.fillStyle='#d48754';g.fillRect(17,16,3,1);
      }
      return small;
    }));
  }
  function idleFrame(seconds,reduced=false){
    if(reduced)return 0;
    const phase=seconds%9;
    if(phase<.9)return [1,2,1,2,0][Math.min(4,Math.floor(phase/.18))];
    return phase>5&&phase<5.18?5:0;
  }
  const reactions=Object.freeze({welcome:[0,1,2,1,2,0],think:[0,3,5,3,0],success:[1,4,4,1,0],oops:[3,5,3,0],explain:[1,0]});
  window.BitboundMentorSprite=Object.freeze({WIDTH,HEIGHT,SCALE,WORLD_WIDTH,WORLD_HEIGHT,POSES,paint,create,worldFrames,idleFrame,reactions});
})();

/* Short portrait reactions. At most one timer; no permanent portrait loop. */
(() => {
  'use strict';
  class PortraitAnimator {
    constructor({paint,setTimer=(callback,delay)=>window.setTimeout(callback,delay),clearTimer=id=>window.clearTimeout(id),reduced=()=>false,visible=()=>true}){
      this.paint=paint;this.setTimer=setTimer;this.clearTimer=clearTimer;this.reduced=reduced;this.visible=visible;this.timer=null;this.generation=0;
    }
    stop(){this.generation++;if(this.timer!==null)this.clearTimer(this.timer);this.timer=null;}
    play(frames){
      this.stop();
      if(!this.visible())return;
      if(this.reduced()){this.paint(frames.includes(4)?4:0);return;}
      const generation=this.generation;let index=0;
      const step=()=>{
        this.timer=null;if(generation!==this.generation||!this.visible())return;
        this.paint(frames[index++]);
        if(index<frames.length)this.timer=this.setTimer(step,180);
      };
      step();
    }
  }
  window.BitboundMentorAnimation=Object.freeze({PortraitAnimator});
})();

/* Cosmetic player poses, advanced only by the existing simulation clock.
   One reusable pose; no timers, random calls, DOM writes or physics mutations. */
(() => {
  'use strict';
  class PlayerAnimator {
    constructor(){
      this.pose={bodyY:0,headX:0,headY:0,blink:false,arm:0,smile:false,motion:'idle',phase:0};
      this.reset();
    }
    reset(){this.gait=0;this.clock=0;this.idle=0;this.landing=0;this.celebration=0;this.neutral();}
    neutral(){
      const p=this.pose;
      p.bodyY=0;p.headX=0;p.headY=0;p.blink=false;p.arm=0;p.smile=false;p.motion='idle';p.phase=0;
      return p;
    }
    land(){this.landing=.18;}
    celebrate(){this.celebration=1.1;}
    update(dt,player,reduced=false,nearGuide=false){
      dt=Math.max(0,Math.min(.1,dt));
      this.clock=(this.clock+dt)%120;
      this.landing=Math.max(0,this.landing-dt);
      this.celebration=Math.max(0,this.celebration-dt);
      const p=this.neutral();
      const resting=player.onGround&&Math.abs(player.vx)<.2&&player.attack<=0&&player.dashTime<=0;
      this.idle=resting?this.idle+dt:0;
      // Controls take priority; mannerisms never delay running, jumping or attacks.
      // Essential action silhouettes remain on in reduced-motion mode.
      if(player.dashTime>0){p.motion='dash';p.phase=1-player.dashTime/.18;return p;}
      if(player.attack>0){p.motion='attack';p.phase=Math.max(0,1-player.attack/.22);return p;}
      if(!player.onGround){p.motion=player.vy<0?'jump':'fall';return p;}
      if(!resting){
        p.motion=Math.abs(player.vx)>5?'run':'walk';
        // Integrate cadence. Multiplying total time by changing velocity made
        // the legs jump to unrelated frames whenever the player accelerated.
        this.gait=(this.gait+dt*Math.min(6,Math.max(1.6,Math.abs(player.vx)*.65)))%1;
        p.phase=this.gait;return p;
      }
      if(reduced)return p;
      if(this.landing>0){p.motion='land';p.phase=1-this.landing/.18;p.bodyY=Math.ceil(this.landing/.18*2);return p;}
      if(this.celebration>0){
        p.motion='cheer';p.phase=(this.clock*2)%1;p.arm=2.6;p.smile=true;
        p.bodyY=Math.sin((1.1-this.celebration)*Math.PI*4)>0?-1:0;
        return p;
      }
      if(this.idle<.7)return p;
      const phase=this.idle%8;
      p.phase=(this.clock*.35)%1;
      p.headY=Math.sin(this.clock*2.2)>.65?-1:0;
      p.blink=(phase>2.2&&phase<2.34)||(phase>5.3&&phase<5.43);
      if(nearGuide&&phase>1&&phase<2){
        p.motion='wave';p.phase=(phase*2)%1;p.arm=2.1+Math.sin((phase-1)*Math.PI*8)*.25;p.smile=true;
      }else if(phase>4&&phase<4.8){
        p.headX=-1; // A quick look back toward the companion.
      }else if(phase>6.3&&phase<7.1){
        p.arm=.45;p.headY=-1; // Loosen the shoulder after standing for a while.
      }
      return p;
    }
  }
  window.BitboundPlayerAnimation=Object.freeze({PlayerAnimator});
})();

/* Original synthetic chipmunk-style babble. No microphone, speech API or download.
   A cached 4.8 s mono buffer loops in Web Audio; no JavaScript playback timer. */
(() => {
  'use strict';
  const SAMPLE_RATE=22050,DURATION=4.8;
  const PITCHES=[520,660,430,580,720,480,610,540];
  const VOWELS=[[800,2200,3400],[500,2700,3800],[650,1500,3200],[1000,2400,3600],[450,1700,3000]];
  const VOICE_PROFILES=Object.freeze({
    BYTE:{pitch:1,seed:317,rhythm:1,gap:1,vowel:0},
    Aster:{pitch:1.20,seed:1103,rhythm:.90,gap:1.22,vowel:2},
    Mira:{pitch:1.48,seed:2707,rhythm:.73,gap:1.45,vowel:1},
    Rook:{pitch:.86,seed:4513,rhythm:1.03,gap:.82,vowel:3},
    Fern:{pitch:1.32,seed:7919,rhythm:.84,gap:1.33,vowel:4}
  });
  function createSamples(speaker='BYTE'){
    const profile=VOICE_PROFILES[speaker]||VOICE_PROFILES.BYTE;
    const {ceil,exp,sin,PI,max,abs,round,floor,imul,min}=Math;
    const samples=new Float32Array(ceil(SAMPLE_RATE*DURATION));
    // Small vowel wavetables avoid evaluating harmonics for every audio sample.
    const tables=VOWELS.map(formants=>{
      const table=new Float32Array(256);let peak=0;
      const weights=Array.from({length:10},(_,i)=>{
        const f=(i+1)*550;
        return (.12+formants.reduce((sum,center)=>sum+exp(-(((f-center)/500)**2)),0))/(i+1);
      });
      for(let n=0;n<256;n++){
        let value=0;for(let h=1;h<=weights.length;h++)value+=weights[h-1]*sin(n/256*PI*2*h);
        table[n]=value;peak=max(peak,abs(value));
      }
      for(let n=0;n<table.length;n++)table[n]/=peak;
      return table;
    });
    let cursor=.08,seed=profile.seed,previousNoise=0;
    for(let syllable=0;syllable<24;syllable++){
      const duration=[.085,.12,.095,.08,.13,.10][syllable%6]*profile.rhythm,table=tables[(syllable+profile.vowel)%tables.length];
      const start=round(cursor*SAMPLE_RATE),length=round(duration*SAMPLE_RATE);
      const pitch=PITCHES[(syllable+profile.vowel)%PITCHES.length]*profile.pitch;let phase=0;
      for(let n=0;n<length&&start+n<samples.length;n++){
        const t=n/SAMPLE_RATE,progress=n/length;
        phase+=pitch*(1+(syllable%2?.2:-.17)*(progress-.5))/SAMPLE_RATE;if(phase>=1)phase-=1;
        const position=phase*256,index=floor(position),fraction=position-index;
        const vowel=table[index]*(1-fraction)+table[(index+1)&255]*fraction;
        seed=(imul(seed,1664525)+1013904223)>>>0;
        const noise=seed/0xffffffff*2-1,consonant=(noise-previousNoise)*max(0,1-t/.025)*.09;
        previousNoise=noise;
        const envelope=min(1,t/.009,(duration-t)/.015);
        samples[start+n]=(vowel*.62+consonant)*max(0,envelope);
      }
      // Several quick syllables, a breath, and a longer break before looping.
      cursor+=duration+(syllable%6===5?.34:[.028,.04,.018][syllable%3])*profile.gap;
    }
    return samples;
  }
  class GibberishVoice {
    constructor(speaker='BYTE'){this.speaker=Object.hasOwn(VOICE_PROFILES,speaker)?speaker:'BYTE';this.context=null;this.buffer=null;this.source=null;this.gain=null;}
    get active(){return this.source!==null;}
    play(context,destination){
      if(this.source&&this.context===context)return;
      this.stop();
      if(this.context!==context||!this.buffer){
        const samples=createSamples(this.speaker),buffer=context.createBuffer(1,samples.length,SAMPLE_RATE);
        buffer.getChannelData(0).set(samples);this.buffer=buffer;this.context=context;
      }
      const source=context.createBufferSource(),gain=context.createGain();
      this.source=source;this.gain=gain;
      try{
        source.buffer=this.buffer;source.loop=true;gain.gain.value=.18;
        source.connect(gain);gain.connect(destination);
        source.onended=()=>{
          source.disconnect();gain.disconnect();
          if(this.source===source){this.source=null;this.gain=null;}
        };
        source.start();
      }catch(error){this.stop();throw error;}
    }
    stop(){
      const source=this.source,gain=this.gain;this.source=null;this.gain=null;
      if(!source)return;
      source.onended=null;
      try{source.stop();}catch{/* Already stopped or not yet started. */}
      source.disconnect();gain.disconnect();
    }
  }
  window.BitboundMentorVoice=Object.freeze({SAMPLE_RATE,DURATION,VOICE_PROFILES,createSamples,GibberishVoice});
})();

/* Encounter definitions stay independent of simulation and drawing. */
(() => {
  'use strict';
  const definitions = {
    slime: {name:'Bit Slime',design:'bit_slime',behavior:'hop',hp:2,w:30,h:24,speed:.8,jump:6,minWorld:0,color:'#72f0a6',voice:'bubble'},
    bat: {name:'Packet Bat',design:'packet_bat',behavior:'fly',hp:2,w:28,h:20,speed:1.7,minWorld:1,color:'#b693ff',voice:'chirp'},
    bug: {name:'Data Beetle',design:'data_beetle',behavior:'shoot',hp:3,w:30,h:24,speed:1.1,minWorld:2,color:'#ffa36d',voice:'clank'},
    frog: {name:'Buffer Frog',design:'buffer_frog',behavior:'hop',hp:2,w:32,h:26,speed:1.2,jump:8,minWorld:0,color:'#8cdc72',voice:'croak'},
    moth: {name:'Spark Moth',design:'spark_moth',behavior:'flyShoot',hp:2,w:32,h:28,speed:1.2,minWorld:1,color:'#ffcc72',voice:'flutter'},
    crab: {name:'Moss Crab',design:'moss_crab',behavior:'walk',hp:4,w:32,h:24,speed:.65,minWorld:2,color:'#80c2a2',voice:'clank'},
    crawler: {name:'Gear Crawler',design:'gear_crawler',behavior:'walk',hp:3,w:32,h:24,speed:1.6,minWorld:3,color:'#dda76b',voice:'rattle'},
    wisp: {name:'Glitch Wisp',design:'glitch_wisp',behavior:'flyShoot',hp:3,w:26,h:30,speed:1.35,minWorld:4,color:'#bd95ff',voice:'wisp'},
    mimic: {name:'Null Mimic',design:'null_mimic',behavior:'hop',hp:4,w:32,h:28,speed:.9,jump:5,minWorld:5,color:'#eacb73',voice:'chomp'}
  };
  const MOBS=Object.freeze(Object.fromEntries(Object.entries(definitions).map(([id,spec])=>[id,Object.freeze({id,...spec})])));
  // Precomputed pools make each encounter selection O(1); common early creatures recur.
  const pools=Object.freeze(Array.from({length:8},(_,level)=>Object.freeze(Object.keys(MOBS).filter(id=>MOBS[id].minWorld<=level))));
  function choose(level,random=Math.random){const pool=pools[Math.max(0,Math.min(7,level|0))];return pool[Math.min(pool.length-1,Math.max(0,Math.floor(random()*pool.length)))];}
  const isFlying=spec=>spec.behavior==='fly'||spec.behavior==='flyShoot';
  window.BitboundEncounters=Object.freeze({MOBS,pools,choose,isFlying,MAX_ENEMIES:18,RESPAWN_SECONDS:18});
})();

/* Original 48px creature atlas. Eight pet poses and six enemy poses are built
   lazily once per species (< 800 KiB total); gameplay is never stored in sprites. */
(()=>{'use strict';
const SIZE=48,PET_IDS=['index_fox','append_slime','slice_owl','sort_bot'],MOB_IDS=['slime','bat','bug','frog','moth','crab','crawler','wisp','mimic'];
function paint(g,id,frame){
 const ink='#101a27',cream='#e9f6de',gold='#e7bc70';
 const r=(c,x,y,w,h)=>{g.fillStyle=c;g.fillRect(x,y,w,h);};
 const p=(c,pts)=>{g.fillStyle=c;g.beginPath();pts.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.closePath();g.fill();};
 const l=(c,w,pts)=>{g.strokeStyle=c;g.lineWidth=w;g.beginPath();pts.forEach(([x,y],i)=>i?g.lineTo(x,y):g.moveTo(x,y));g.stroke();};
 const step=[0,2,0,-2,0,0,3,-3][frame%8],blink=frame===5,skill=frame>=6,warn=frame===4;
 const eye=(x,y,wide=5,color='#9ceeff')=>{if(blink){r(ink,x,y+3,wide,1);return;}r(cream,x,y,wide,6);r(color,x+2,y+1,wide-2,4);r(ink,x+wide-2,y+1,2,4);r('#fff',x+wide-2,y+1,1,1);};
 const legs=(xs,y,color)=>{xs.forEach((x,i)=>{const off=i%2?step:-step;p(ink,[[x,y],[x+7,y],[x+6,y+8+off],[x+9,y+10],[x-2,y+10],[x-2,y+7+off]]);r(color,x,y+2,5,5);r(cream,x-1,y+8,7,1);});};
 if(id==='index_fox'){
   p(ink,[[17,34],[8,38],[0,32],[1,18-step],[5,16-step],[11,28],[17,28]]);
   p('#357da1',[[16,33],[8,35],[3,30],[3,21-step],[7,24],[11,31]]);p('#d6f2e9',[[2,19-step],[5,18-step],[9,27],[5,27],[3,24]]);
   legs([17,31],35,'#3d667c');p(ink,[[14,26],[34,25],[41,33],[39,40],[15,40],[12,34]]);p('#5497b3',[[17,28],[33,27],[38,32],[36,37],[17,38]]);p('#d8ebe0',[[25,28],[33,28],[35,35],[28,38],[23,35]]);
   p(ink,[[15,18],[13,4],[19,1],[26,11],[32,11],[40,1],[43,5],[42,24],[47,27],[43,33],[23,32],[17,27]]);
   p('#62bdd9',[[17,8],[19,5],[25,15],[34,15],[40,5],[40,22],[37,26],[44,28],[40,30],[23,29],[19,23]]);
   p('#344f74',[[17,8],[19,6],[23,15],[19,14]]);p('#a2d8e4',[[37,14],[40,7],[40,17]]);
   p('#a1e2e5',[[20,18],[25,15],[32,17],[34,21],[22,22]]);eye(32,20,6,'#607896');
   p(cream,[[29,27],[43,26],[44,29],[38,32],[31,31],[26,28]]);r(ink,43,26,4,3);r('#c5dee4',23,25,2,2);
   p('#8f4654',[[17,30],[30,32],[32,35],[20,35],[16,41],[13,39]]);r('#ecc790',20,32,8,1);
   r('#715b41',18,35,7,7);r('#b79664',19,36,5,2);
   if(skill){l(gold,1,[[34,4],[36,0],[38,4]]);r('#ffedb4',43,14,3,3);}
 }else if(id==='append_slime'||id==='slime'){
   const friendly=id==='append_slime',dark=friendly?'#277c6e':'#764862',mid=friendly?'#52c897':'#b57483',light=friendly?'#99ebaf':'#e7a8a1',s=skill?-3:step;
   p(ink,[[4,41],[1,35],[6,23+s],[12,14+s],[29,11+s],[40,19+s],[47,36],[42,43],[12,46]]);
   p(dark,[[5,38],[7,24+s],[14,17+s],[29,14+s],[38,22+s],[44,36],[39,41],[13,43]]);
   p(mid,[[9,34],[11,23+s],[18,17+s],[29,16+s],[36,23+s],[39,35],[32,40],[15,39]]);
   p(light,[[12,23+s],[18,18+s],[25,17+s],[22,22+s],[15,27+s]]);r('#ddffe3',15,20+s,5,2);
   for(let n=0;n<4;n++)r(light,7+n*9,37+n%2*3,3,2);
   eye(17,27+s,5,friendly?'#4b9a7d':'#842735');eye(30,26+s,5,friendly?'#4b9a7d':'#842735');l(ink,1,[[24,35+s],[27,37+s],[31,35+s]]);
   if(friendly){l('#668050',2,[[23,15+s],[25,6+s]]);p('#a4da83',[[24,9+s],[18,7+s],[16,2+s],[23,3+s],[26,7+s],[30,1+s],[35,3+s],[33,8+s]]);r('#e3f5bd',20,4+s,3,1);if(skill){r(cream,23,19,3,10);r(cream,20,22,9,3);}}
   else{p('#ddd3b7',[[14,13+s],[19,6+s],[25,11+s],[31,5+s],[34,13+s]]);l('#49343f',1,[[18,26+s],[23,28+s]]);}
 }else if(id==='slice_owl'||id==='bat'||id==='moth'){
   const owl=id==='slice_owl',bat=id==='bat',wing=owl?'#937cb9':bat?'#7a547d':'#c78969',shade=owl?'#604d83':bat?'#3b344e':'#705474';
   const flap=skill?12:step*3;
   p(ink,[[23,21],[12,9-flap],[3,6],[0,15+flap],[5,31],[17,36],[23,29],[31,37],[43,29],[48,14+flap],[44,6],[34,9-flap],[27,21]]);
   p(wing,[[21,25],[12,13-flap],[4,10],[3,16+flap],[9,29],[17,31]]);p(wing,[[28,25],[36,13-flap],[44,10],[45,16+flap],[39,29],[31,31]]);
   for(let j=0;j<3;j++){l(shade,2,[[22,27],[8+j*4,16+j*5]]);l(shade,2,[[27,27],[40-j*4,16+j*5]]);}
   p(ink,[[14,14],[16,3],[22,9],[27,8],[34,3],[36,17],[34,37],[26,44],[17,39]]);p(shade,[[17,14],[17,8],[23,12],[28,12],[33,8],[33,34],[26,40],[19,36]]);
   if(owl){p('#d6c7df',[[16,20],[20,16],[25,19],[30,16],[34,20],[32,30],[25,36],[18,30]]);eye(18,21,5,'#bf963f');eye(28,21,5,'#bf963f');p(gold,[[23,28],[29,28],[26,33]]);for(let j=0;j<3;j++)p('#a68abf',[[19+j*5,34],[23+j*5,34],[21+j*5,38]]);legs([17,28],35,gold);if(skill)l('#cceaff',2,[[2,38],[14,41],[26,42],[43,37]]);}
   else if(bat){r('#bc8094',21,12,8,6);eye(18,23,5,'#e0806e');eye(29,23,5,'#e0806e');p('#faf0cd',[[21,32],[24,32],[23,36]]);p('#faf0cd',[[28,32],[31,32],[29,36]]);}
   else{for(const x of [7,34]){r('#edc989',x,20,7,8);r('#70416a',x+2,22,3,4);}r('#f3d49c',23,13,5,27);l(ink,2,[[23,14],[18,8],[17,3]]);l(ink,2,[[27,14],[32,8],[34,4]]);eye(22,18,4,'#d48956');}
 }else if(id==='sort_bot'){
   legs([11,29],35,'#727e85');p(ink,[[7,12],[38,12],[42,17],[41,38],[34,42],[10,40],[5,31]]);r('#987440',9,16,28,22);r('#d9b85f',11,15,24,19);r('#ffe09b',12,16,21,2);
   r(ink,12,20,24,14);r('#29444c',14,22,20,10);r('#65bba9',15,23,18,1);
   if(blink){r('#baf5d6',17,27,5,1);r('#baf5d6',27,27,5,1);}else{r('#bcf4d7',17,26,4,5);r('#bcf4d7',28,26,4,5);r('#f7fff3',17,26,1,2);}
   r('#313b45',22,5,3,8);r(ink,19,2,9,5);r(skill?'#fff0a2':'#81c9b8',21,3,5,3);
   for(let side=0;side<2;side++){const x=side?39:2,y=skill?(side?17:25):24+(side?step:-step);r(ink,x,y,7,13);r('#c9a45c',x+1,y+1,5,8);r('#a8b5b1',x,y+10,6,3);r('#d0e1cc',x+1,y+10,2,2);}
   r('#504638',15,36,18,4);for(let n=0;n<4;n++)r(skill?'#92ead5':'#9c9e77',17+n*4,37,2,2);r('#edf0c1',10,16,2,2);r('#edf0c1',35,16,2,2);
   if(skill)for(let n=0;n<3;n++)l('#ffe4a8',1,[[5+n*16,4],[7+n*16,8],[4+n*16,10]]);
 }else if(id==='frog'){
   legs([3,31],33,'#64876b');p(ink,[[5,37],[7,22],[13,14],[34,13],[42,25],[44,37],[38,43],[11,43]]);p('#668566',[[9,34],[11,23],[18,17],[31,17],[38,25],[39,37],[14,40]]);p('#b9cb8a',[[17,28],[33,28],[36,37],[16,38]]);
   for(const x of [10,29]){r(ink,x,8+step,11,15);r('#bdd091',x+2,10+step,7,10);eye(x+3,12+step,5,'#bda251');}l(ink,2,[[15,30],[25,33],[37,29]]);for(let n=0;n<4;n++)r('#a9b57b',12+n*7,22+n%2*3,3,2);if(warn)l('#bc7682',3,[[30,33],[42,33],[47,29]]);
 }else if(id==='bug'||id==='crab'||id==='crawler'){
   const crab=id==='crab',bug=id==='bug',shell=crab?'#728c80':bug?'#976b87':'#977557',hi=crab?'#a9c0a0':bug?'#d39eaa':'#d0af7d';
   for(let n=0;n<4;n++){const x=5+n*11;l(ink,4,[[x+4,29],[x,36+(n%2?step:-step)],[x+3,44]]);l('#a7ac9b',1,[[x+3,31],[x+1,37],[x+3,42]]);}
   p(ink,[[4,32],[5,20],[13,11],[33,10],[44,21],[46,33],[33,39],[13,38]]);p(shell,[[7,30],[9,20],[16,14],[31,13],[40,22],[42,31],[32,35],[15,35]]);
   if(crab){p(hi,[[12,25],[17,14],[30,13],[36,23],[30,31],[17,31]]);for(const x of [1,37]){p(ink,[[x,19-step],[x+4,11-step],[x+9,15-step],[x+10,27],[x+4,33]]);p('#ba9b7a',[[x+2,19-step],[x+4,15-step],[x+6,22],[x+8,16-step],[x+8,26],[x+4,29]]);}eye(18,30,4,'#907456');eye(29,29,4,'#907456');}
   else if(bug){p(hi,[[10,20],[19,13],[24,15],[23,32],[13,30]]);p('#714b6a',[[27,15],[33,15],[39,23],[34,32],[27,33]]);l(ink,2,[[25,14],[25,34]]);eye(30,28,5,'#e7c876');p('#f0d7b2',[[37,32],[44,28],[42,36]]);r('#edc48f',38,26,4,3);}
   else{for(let n=0;n<4;n++){r(ink,8+n*8,16+n%2*2,3,18);r(hi,11+n*8,18+n%2*2,4,5);}eye(35,24,5,'#df875e');l(ink,2,[[39,21],[39,13],[46,10]]);r('#c1c7a6',44,8,3,3);}
 }else if(id==='wisp'){
   p(ink,[[24,0],[35,12],[42,25],[37,36],[43,45],[30,42],[22,48],[12,43],[5,46],[10,33],[5,22],[15,9]]);p('#655686',[[24,4],[32,15],[38,26],[32,36],[35,42],[24,39],[18,44],[13,38],[14,30],[9,23],[18,12]]);p('#ada5c4',[[23,13],[32,20],[34,29],[27,36],[17,33],[14,24]]);eye(16,25+step,5,'#71bbae');eye(28,25+step,5,'#71bbae');r('#eee6d3',23,33,3,4);for(let n=0;n<3;n++)r('#b5d8c7',4+n*19,12+(n*11+frame*5)%28,2,3);
 }else if(id==='mimic'){
   const jaw=warn?10:step+3;r(ink,3,22-jaw,43,23+jaw);r('#977153',5,24-jaw,39,17+jaw);r('#e2bb72',6,26-jaw,37,4);r('#2a202d',5,32-jaw,39,8+jaw);
   for(let n=0;n<6;n++){p(cream,[[7+n*6,32-jaw],[12+n*6,32-jaw],[9+n*6,38-jaw]]);p(cream,[[8+n*6,40],[13+n*6,40],[10+n*6,35]]);}
   r('#dab471',7,22-jaw,3,10);r('#dab471',38,22-jaw,3,10);r('#f0d49c',22,27-jaw,7,6);r('#302936',24,29-jaw,3,4);r('#ef967d',12,27-jaw,5,2);r('#ef967d',33,27-jaw,5,2);legs([8,31],36,'#4b434b');
 }
 if(warn&&MOB_IDS.includes(id)){r('#f6ca86',22,2,3,7);r('#f6ca86',22,11,3,2);}
}
function frameAt(t,reduced=false,cheering=false){if(reduced)return 0;if(cheering)return 6+Math.floor(t*8)%2;return t%6>5.8?5:Math.floor(t*8)%4;}
function create(document){const cache=new Map();function frames(id){if(!PET_IDS.includes(id)&&!MOB_IDS.includes(id))return null;if(!cache.has(id))cache.set(id,Object.freeze(Array.from({length:PET_IDS.includes(id)?8:6},(_,i)=>{const c=document.createElement('canvas');c.width=c.height=SIZE;paint(c.getContext('2d'),id,i);return c;})));return cache.get(id);}
function draw(g,id,x,y,w=SIZE,h=SIZE,frame=0,dir=1){const a=frames(id);if(!a)return false;g.save();g.imageSmoothingEnabled=false;g.translate(Math.round(x)+(dir<0?w:0),Math.round(y));g.scale(dir<0?-1:1,1);g.drawImage(a[Math.max(0,frame|0)%a.length],0,0,w,h);g.restore();return true;}
return Object.freeze({draw,frames,get bytes(){let n=0;for(const a of cache.values())n+=a.length*SIZE*SIZE*4;return n;}});}
window.BitboundCreatureSprites=Object.freeze({SIZE,PET_IDS,MOB_IDS,paint,frameAt,create});})();
